DROP TABLE IF EXISTS entries;

CREATE TABLE entries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    lat INTEGER NOT NULL DEFAULT 0,
    long INTEGER NOT NULL DEFAULT 0,
    author TEXT NOT NULL,
    verified BOOLEAN NOT NULL DEFAULT false
);